version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: beauty_salon_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/beauty_salon_db
      - TELEGRAM_BOT_TOKEN=ВАШ_ТОКЕН_ОТ_BOTFATHER # <-- ЗАМЕНИТЕ ЭТОТ ТОКЕН!
      - PORT=5000
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: postgres:13-alpine
    container_name: beauty_salon_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=beauty_salon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
